### ISSUE TITLE
play music from youtube and lofi radio don't work

### ISSUE THREAD

**Issue by qvieth** [HACKER097/wisdom-tree#11]
no result show when i use these features, also once I enter search bar of youtube, there's no way to go back (expect Esc would let me go back to the menu).

**Comment by tanay-pingalkar** [comment]
same

**Comment by HACKER097** [comment]
Looks like its an issue with pytube, https://github.com/pytube/pytube/issues/1060

**Comment by thomashillen** [comment]
Issue explained [here ](https://github.com/pytube/pytube/issues/1060#issuecomment-884541186).

**Comment by HACKER097** [comment]
Experimental fix is already here! `python -m pip install git+https://github.com/Zeecka/pytube@fix_1060`.

**Comment by HACKER097** [comment]
Will close the issue when the fix is implemented in the pypi repo.

**Comment by HACKER097** [comment]
ok, it has been fixed, pld do `pip install --upgrade wisdom-tree`
