### ISSUE TITLE
Gobbles a core during breaks

### ISSUE THREAD

**Issue by glotchimo** [HACKER097/wisdom-tree#14]
I've seen it multiple times now where, when a break starts, the script grabs and holds an entire core for the duration of the break. I don't have any concrete profiling data yet but am opening this to track and see if anybody else sees this behavior.

**Comment by HACKER097** [comment]
Thanks for reporting this, I would have never caught it. I forgot to add fps limiters in the pause and break loops, so they refresh as many times as the core allows, this has now been fixed along with some other performance improvements.

Update using `pip3 install --upgrade wisdom-tree`
