### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by IcyFlamingArrow** [HACKER097/wisdom-tree#15]
Hello,

Can you create a release in order to allow users to package `wisdom-tree`?

Thank you

**Comment by HACKER097** [comment]
I don't understand your request, can you explain it better?

**Comment by IcyFlamingArrow** [comment]
My apologies about by vagueness.

What I am referencing is enclosed by the red box in the screenshot.

[https://ibb.co/jZdbmWw](url)

**Comment by HACKER097** [comment]
aah ok, I've created a release, its `0.0.16` instead of `0.0.1` because I want to keep it same as the pypi package. Can I close this issue now?

**Comment by IcyFlamingArrow** [comment]
Yes, you are able to close this issue now.

Thank you.
