### ISSUE TITLE
100% core usage when paused.

### ISSUE THREAD

**Issue by Casul51** [HACKER097/wisdom-tree#16]
I just pause and entire core (not cpu) at 100% load

**Comment by Casul51** [comment]
Operating System: Arch Linux
KDE Plasma Version: 5.22.3
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.2
Kernel Version: 5.13.4-zen2-1-zen (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15,6 GiB of RAM

**Comment by Casul51** [comment]
```
python -V                                                                                                                                                                                       
Python 3.9.6
```

**Comment by HACKER097** [comment]
This issue has been fixed, please see https://github.com/HACKER097/wisdom-tree/issues/14
