### ISSUE TITLE
wisdom-tree broke after new update

### ISSUE THREAD

**Issue by qvieth** [HACKER097/wisdom-tree#17]
Running wisdom-tree after update throws this

![image](https://user-images.githubusercontent.com/71810726/128163815-22993bcf-182b-493a-950b-bb360aa98928.png)

**Comment by HACKER097** [comment]
Do you have python-vlc installed?

**Comment by qvieth** [comment]
Yes I do

**Comment by HACKER097** [comment]
You also need vlc installed o your system

**Comment by qvieth** [comment]
Oh, sorry I don't have that package, but I just tried installing python-vlc and rerun wisdom-tree, the error seems to be the same
![image](https://user-images.githubusercontent.com/71810726/128170051-fdac8a02-3ba5-4fd9-98d9-fb2ebfe432c4.png)

**Comment by qvieth** [comment]
oh wait let me install vlc

**Comment by qvieth** [comment]
Installing both python-vlc and vlc fix the issue, @HACKER097

**Comment by qvieth** [comment]
Thank you, @HACKER097

**Comment by HACKER097** [comment]
yay! with vlc, wisdom-tree can stream directly from YouTube, playing music is a lot faster.

**Comment by qvieth** [comment]
@HACKER097 hmm, YouTube searching seems to not working again, still the long waiting prompt, but after a while it throws ERROR GETTING AUDIO message.

**Comment by qvieth** [comment]
![image](https://user-images.githubusercontent.com/71810726/128171255-7864b786-ef32-4287-a250-ae7c8b597ebb.png)

**Comment by HACKER097** [comment]
have you updated pytube?

**Comment by qvieth** [comment]
oh i just updated and now youtube works great!!, many thanks again @HACKER097

**Comment by qvieth** [comment]
@HACKER097 lo-fi radio throws this, did I miss something again
![Screenshot from 2021-08-04 18-20-23](https://user-images.githubusercontent.com/71810726/128172732-f39699a0-5dc7-46bf-b1df-18173646b43b.png)

**Comment by qvieth** [comment]
![Screenshot from 2021-08-04 18-30-00](https://user-images.githubusercontent.com/71810726/128173497-33e51b6d-e480-41e3-8d07-d0b281bdb8d2.png)
here's the full message
