### ISSUE TITLE
Unable to play any of the Lo-Fi radios

### ISSUE THREAD

**Issue by lukeberry99** [HACKER097/wisdom-tree#20]
Hi,

Something has suddenly stopped working and I'm now unable to listen to any of the Lo-Fi radios, I haven't tried playing from youtube yet but lo-fi radio 1 was my jam.

![image](https://user-images.githubusercontent.com/1644147/132211199-3d4a05aa-2d38-4299-aab2-4fee90d51e58.png)

What's the best way to get the log output?

**Comment by HACKER097** [comment]
This could be an issue with pytube, please run `pip install --upgrade pytube` and try again.

**Comment by pdgreg** [comment]
Hello!

I'm running into the same issue as @lukeberry99. I've attached a screenshot to my comment displaying my issue:
<img width="1166" alt="Screen Shot 2021-11-24 at 10 46 01 PM" src="https://user-images.githubusercontent.com/88806542/143393263-55ab7b2e-a92b-4872-ac5e-9699d314007e.png">

I have the latest version of _sdl2_mixer_ installed via Brew. I also have the latest version of pytube installed via PIP:
<img width="584" alt="Screen Shot 2021-11-24 at 10 50 39 PM" src="https://user-images.githubusercontent.com/88806542/143393463-8344c92a-56de-4057-8cb4-bcefd59a33ba.png">

Do you have any other recommendations as to how I can get the Lo-Fi Radio features working?
