### ISSUE TITLE
Upgrading widsom tree loses all tree progress

### ISSUE THREAD

**Issue by lukeberry99** [HACKER097/wisdom-tree#21]
Not sure if this is intentional, but 

```bash
pip install --upgrade wisdom-tree
```
Removes all tree progress. Gotta start my baby  all over again.

**Comment by HACKER097** [comment]
This is something I'll need to fix, for now you can backup your `~/.local/lib/python3.x/site-packages/wisdom_tree/res/treedata` file and replace it after upgrading.
