### ISSUE TITLE
[FEATURE REQUEST] Escape button for going back to the previous menu or escaping input field

### ISSUE THREAD

**Issue by qvieth** [HACKER097/wisdom-tree#26]
After started tree-wisdom, user can change basic song by pressing left or right arrow. If user choose pressing up or down arrow, they will go to select time menu. But then they have no way of going back to the first menu which allow user to change basic song with left and right arrow.

Also, pressing escape doesn't allow going back while the user is in "Custom Timer" or "Select YouTube Song" input field. (I tried to go back by pressing Ctr+C and weird bug happens).

https://user-images.githubusercontent.com/71810726/135784065-9d9fa2bb-0cd1-47ab-9a58-ada0d6f2e5a5.mp4

Expected Behavior: Expect escape also allow going back to the previous menu or escape input field.

**Comment by HACKER097** [comment]
I am not exactly sure how to fix this, there is no way to tell which key(s) is pressed without pressing enter first.

**Comment by HACKER097** [comment]
This has been fixed in `wisdom-tree 0.1.5`. You can now type `q` in the search to exit it.
