### ISSUE TITLE
[Bug] YouTube is playing random videos

### ISSUE THREAD

**Issue by JsonLinesCode** [HACKER097/wisdom-tree#27]
I tried to use the youtube video feature (with [this link ](https://youtu.be/mX2L_lVSkOY)) and the song played is [another totally unrelated video ](https://www.youtube.com/watch?v=_OjMYOvkb48)

**Comment by HACKER097** [comment]
Should be fixed now, please update using `pip3 install --upgrade wisdom-tree` and see if its still a problem.

**Comment by JsonLinesCode** [comment]
Yup, looks like it's fixed ! Thanks
