### ISSUE TITLE
End timer now selection is calling breakover

### ISSUE THREAD

**Issue by JB-pythonic-py** [HACKER097/wisdom-tree#3]
def breakdisplay(self, maxx, maxy):
			self.secondsleft = int(self.breakendtime)-int(time.time())
			timertext = "Break ends in: " + str(int(self.secondsleft/60)).zfill(2) + ":" + str(self.secondsleft%60).zfill(2)
			self.stdscr.addstr(int(maxy*10/11), int(maxx/2-len(timertext)/2), timertext)

			if self.secondsleft == 0:
				mixer.music.unpause()
				self.isbrake = False
				self.breakover = True
				self.alarm.play()
`
![](https://i.imgur.com/bJKvVWW.png)

Selecting "End timer now" is calling breakover, but ending the timer during pomodoro clock could call a new method.

self.pomodoroover

Then this can display a message about the pomodoro being over instead of the break.

**Comment by HACKER097** [comment]
Has been fixed.
