### ISSUE TITLE
wisdom-tree can’t connect to the internet

### ISSUE THREAD

**Issue by blochhamiltonian** [HACKER097/wisdom-tree#32]
I was wondering if anyone knows of a fix for this bug. I’m using the latest version as of Jan 24 2021 at 21:53 UTC. I found wisdom-tree today unable to load music from YouTube, and it seemed to not be connecting to the Internet at all. How would you recommend I fix this issue? 

Thank you.

**Comment by blochhamiltonian** [comment]
I get the error message, “ERROR GETTING AUDIO, PLEASE TRY AGAIN”

**Comment by blochhamiltonian** [comment]
And for the lofi radio, I get “UNABLE TO CONNECT, PLEASE CHECK INTERNET CONNECTION”

**Comment by HACKER097** [comment]
https://github.com/pytube/pytube/issues/1199
Its a problem with pytube

**Comment by HACKER097** [comment]
Please update pytube
