### ISSUE TITLE
Unable to play youtube videos 

### ISSUE THREAD

**Issue by blochhamiltonian** [HACKER097/wisdom-tree#33]
Sorry to post this again, but I am running the same version, and after having fixed the pytube problem, it was working for a while, but now after booting up wisdom-tree for the first time in a while, and I try to play music from youtube it says

“ERROR GETTING AUDIO, PLEASE TRY AGAIN”

Did YouTube change something, rendering the previous PyTube fix now unworkable?

**Comment by HACKER097** [comment]
This project is abandoned. I have gotten busy with other things, and won't be able to make any more commits for a very long time.

**Comment by HACKER097** [comment]
This has been fixed thanks to Pytube.
