### ISSUE TITLE
Audio Device Error w/ Pulse Audio on WSL

### ISSUE THREAD

**Issue by connorkas** [HACKER097/wisdom-tree#6]
Upon running the final command to finishing setting up, I'm stuck on this error.
`~/wisdom-tree(main) » python3 main.py               
shared memfd open() failed: Function not implemented
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    mixer.init()
pygame.error: ALSA: Couldn't open audio device: No such file or directory`

Does wisdom-tree only work on linux based operated systems? I assume it just can't find an audio driver compatible with WSL.

**Comment by HACKER097** [comment]
I haven't tested on WSL, but wisdom tree does work on Windows, so you don't need to use WSL.
